### ISSUE TITLE
Order/Configure/Apply dev DNS

### ISSUE THREAD

**Issue by steveoh** [agrc/Chalkdust#2]
please order the dns `chalkdust.dev.utah.gov`, configure the dns records with the standard firebase ips, and apply the dns to `ut-dts-agrc-chalkdust-dev` firebase hosting.

**Comment by nathankota** [comment]
- [ ] DNS request (INC1499146)
- [ ] Firebase hosting request (TBD)

**Comment by steveoh** [comment]
The two requests can be done in tandom. It just won't work in firebase until the first one is completed.
