### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by stdavis** [agrc/Chalkdust#22]
addressediting.utah.gov is throwing CORS errors when attempting to hit the `send-email-service` from this endpoint. I can see that the [CORS headers are being set](https://github.com/agrc/Chalkdust/blob/62ffedc1096af42bc5d79598bac6e40983a8d14f/function/index.js#L74) so I'm not sure what's going on.

![image](https://user-images.githubusercontent.com/1326248/179077918-9e9b6018-84a4-4b1e-9baf-06709d928878.png)

**Comment by steveoh** [comment]
i think this was a blip in GCP. The function does have cors enabled but the logs show that the function couldn't be started due to lack of resources. Which is odd in a serverless environment. Hopefully it doesn't happen often. Let's monitor the logs and maybe build some retry login into the widget.
